- pkg/manifest/dynamodb.go
* Increase number of retries to put entries into dynamodb
> increase retries

- .gitignore
- Dockerfile.test
- Jenkinsfile
- Makefile
- docker-compose.test.yml
- pkg/manifest/dynamodb.go
- pkg/manifest/dynamodb_test.go
* Added support for Dockerized testing
* Added local-Dynamodb docker container for testing
* Added initial tests for manifest creation and. fetching
> DynamoDB testing

- lambda/authorizer/handler/handler.go
- terraform/data.tf
- terraform/gateway.tf
- terraform/upload_service.yml
Adds the [datasest-service lambda](https://github.com/Pennsieve/datasets-service) as a new endpoint to the API.
First iteration of the `/datasets/trashcan` spec.
> Datasets Service

- terraform/data.tf
- terraform/gateway.tf
- terraform/upload_service.yml
Adds the packages-service Lambda to our API Gateway.
Initial spec for `/packages/restore`
> Add packages-service to gateway

- terraform/upload_service.yml
to support:
- submit a dataset proposal for review
- withdraw a dataset proposal from review
- accept a dataset proposal
- reject a dataset proposal
> add workflow API endpoints for Dataset Proposals

- terraform/upload_service.yml
This reverts commit b5ba233e9d55df1f3def0149e4b90ec986e75f1a.
> Revert PR 20

- .github/workflows/readme.yml
- terraform/upload_service.yml
Reverting #22 . It worked with API Gateway, but Readme did not like the OpenAPI spec.
> Revert PR22

- terraform/data.tf
- terraform/gateway.tf
- terraform/upload_service.yml
- adds integratioon service to gateway
> adds integratioon service to gateway

- terraform/data.tf
- terraform/gateway.tf
- terraform/upload_service.yml
- adds the rehydration service
> adds rehydration service

- terraform/data.tf
- terraform/gateway.tf
> updates service arn

- terraform/upload_service.yml
- updates openAPI interface for rehydration service
> updates rehydration service interface

- terraform/upload_service.yml
- adds GET integrations endpoint docs
> adds docs for integrations GET endpoint

- terraform/upload_service.yml
> fixes formatting

- terraform/upload_service.yml
> updates yml for integration service

- terraform/data.tf
- terraform/gateway.tf
- terraform/upload_service.yml
- adds account service to gateway
`/pennsieve-accounts/{accountType}`
> feature: adds account-service to gateway

- terraform/upload_service.yml
> adds accounts POST to gateway

- terraform/upload_service.yml
- updates yml for POST /accounts
- update response code to 201 for POST
> fix: updates yml for POST /accounts

- terraform/upload_service.yml
- fix build https://github.com/Pennsieve/pennsieve-go-api/actions/runs/8481598290 (typo fix)
> fixes build

- terraform/upload_service.yml
- adds GET endpoints for account service
> feature: adds GET endpoints for account service

- terraform/data.tf
- terraform/gateway.tf
- terraform/upload_service.yml
- adds compute node service endpoints
> adds compute node service endpoints

- terraform/gateway.tf
- terraform/upload_service.yml
- adds app-deploy-service
- adds name and description of the compute node
> feature: App Deploy Service

- terraform/upload_service.yml
- adds deploy endpoint to applications
> feature: adds deploy endpoint

- terraform/upload_service.yml
- adds account to deploy payload
> fix: adds account to payload

- terraform/upload_service.yml
> feature: adds workflows endpoint

- terraform/upload_service.yml
- updates workflows payload (adds commandArguments field)
> fix: updates workflows payload to add command arguments

- terraform/upload_service.yml
add entry points for enable and disable tracking of external repos
> GitHub Service: add entry points for tracking repos

- terraform/upload_service.yml
Initialized the schemas paths and security for drs-service.
> initialized schemas and paths for drs-service

- terraform/upload_service.yml
- adds GET integrations endpoint - that returns all integrations
Related: https://github.com/Pennsieve/integration-service/pull/44
> feature: adds GET integrations endpoint

- terraform/upload_service.yml
Related: https://github.com/Pennsieve/integration-service/pull/45
This PR adds the PUT /integrations endpoint
> feature: adds PUT /integrations

- terraform/data.tf
- terraform/gateway.tf
- terraform/upload_service.yml
resubmit my initialization for schemas,paths and security in upload_service.yml
> resubmit my initialization for schemas,paths and security

- terraform/upload_service.yml
add drs service info api to upload service
> add drs service info api to upload service

- terraform/upload_service.yml
- adds new endpoints to support the concept of workflows and workflow instances:
```
POST /workflows/instances - initiates a workflow
GET /workflows/instances - retrieves workflow instances
GET /workflows/instances/{id} - retrieves a workflow instance
PUT /workflows/instances - updates a workflow instance (for example updates the end datetime of a running workflow instance)
```
- marks old endpoints as `deprecated`
> feature: adds new workflow endpoints and deprecates old related ones

- lambda/authorizer/handler/handler.go
- adds logging to prep for future work regarding authorizers
> debug: logs event

- lambda/authorizer/authorizers/authorizer.go
- lambda/authorizer/authorizers/dataset_authorizer.go
- lambda/authorizer/authorizers/dataset_authorizer_test.go
- lambda/authorizer/authorizers/manifest_authorizer.go
- lambda/authorizer/authorizers/user_authorizer.go
- lambda/authorizer/authorizers/user_authorizer_test.go
- lambda/authorizer/authorizers/workspace_authorizer.go
- lambda/authorizer/factory/factory.go
- lambda/authorizer/factory/factory_test.go
- lambda/authorizer/handler/handler.go
- lambda/authorizer/manager/claims_manager.go
- lambda/authorizer/mappers/mappers.go
- lambda/authorizer/mocks/mocks.go
- lambda/authorizer/service/identity_source_service.go
> more refactoring

- lambda/authorizer/factory/factory.go
- lambda/authorizer/helpers/helpers.go
- lambda/authorizer/helpers/helpers_test.go
- handles params that are passed URL encoded by client
> fix: adds url decoding and refactors factory logic

- lambda/authorizer/handler/handler.go
> fix: consistent error handling

- terraform/cloudwatch.tf
- temporarily revert datadog changes
- This will be re-instated as part of: https://app.clickup.com/t/868aryga5
> fix: reverts datadog changes

- lambda/authorizer/handler/handler.go
The function `validateCognitoJWT` returns the same error for four different conditions. The different conditions can only be determined by turning on debug logging.
This PR removes the debug logging and returns more detailed errors for each condition. Logging info is not lost, since the caller now logs the errors being returned.
> Replace debug logging with detailed errors

- lambda/authorizer/authorizers/authorizer.go
- lambda/authorizer/authorizers/dataset_authorizer.go
- lambda/authorizer/authorizers/dataset_authorizer_test.go
- lambda/authorizer/authorizers/manifest_authorizer.go
- lambda/authorizer/authorizers/manifest_authorizer_test.go
- lambda/authorizer/authorizers/user_authorizer.go
- lambda/authorizer/authorizers/user_authorizer_test.go
- lambda/authorizer/authorizers/workspace_authorizer.go
- lambda/authorizer/authorizers/workspace_authorizer_test.go
The label for team claims in the *Claim* struct is `team_claims`.
> Fix Team Claim generation

- terraform/data.tf
- terraform/gateway.tf
- terraform/upload_service.yml
**ClickUp Ticket:** [868auytez](https://app.clickup.com/t/868auytez)
See https://github.com/Pennsieve/imaging-service/pull/1 for details about the service and implementation
I need to add this to our dev API so that a front-end viewer POC can be developed against it.
> 868auytez add imaging service and MicroCT session route

- terraform/upload_service.yml
- adds new endpoint for retrieving processor logs
> feature: adds new endpoint for retrieving processor logs

- terraform/upload_service.yml
**ClickUp Ticket:** [868bffvuc](https://app.clickup.com/t/868bffvuc)
Adds APIs for writing and fetching the statuses of workflow instances and their processors.
Related PR: https://github.com/Pennsieve/integration-service/pull/58
```
...
+   /workflows/instances/{id}/status:
+     get:
+       summary: Get the statuses for a workflow instance
+       description: |
+         Retrieves the status of for the workflow instance and each of its processors
+       x-amazon-apigateway-integration:
+         $ref: '#/components/x-amazon-apigateway-integrations/integration-service'
+       operationId: getWorkflowInstanceStatus
+       security:
+         - token_auth: [ ]
+       tags:
+         - Integration Service
+       parameters:
+         - in: path
+           name: id
+ …
```
> 868bffvuc workflow instance status API

- terraform/upload_service.yml
Related: https://app.clickup.com/t/868bu6jyc
- updates endpoints to use workspace authorizer
> fix: updates authorizer for workflows GET endpoints

- terraform/upload_service.yml
- updates docs to reflect required fields
> fix: updates docs

- terraform/upload_service.yml
**ClickUp Ticket:** [868cdq5ce](https://app.clickup.com/t/868cdq5ce)
**Related PR:** https://github.com/Pennsieve/integration-service/pull/63
Adds the new `PUT /workflows/instances/{id}/processor/{processorId}/status` endpoint and updates the request object for both status endpoints
> 868cdq5ce update workflow instance processor status

- terraform/upload_service.yml
Ticket: https://app.clickup.com/t/868dm7dfa
- adds endpoint to facilitate adding an application to the App Store
Related: https://github.com/Pennsieve/app-deploy-service/pull/78
**Terraform Plan**
```
***** Refreshing State and Upgrading Modules *****
Upgrading modules...
- uploads_module in ../../../../../../../pennsieve-go-api/terraform
Initializing the backend...
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding newrelic/newrelic versions matching "~> 2.37.0"...
- Finding datadog/datadog versions matching "~> 2.23.0"...
- Finding hashicorp/aws versions matching "5.50.0"...
- Using previously-installed datadog/datadog v2.23.0
- Using previously-installed hashicorp/aws v5.50.0
- Using previously-installed newrelic/newrelic v2.37.0
╷
│ …
```
> feature: Add to App Store endpoint

- terraform/upload_service.yml
- updates wording for Create Workflow
> fix: updates wording for Create Workflow

- terraform/upload_service.yml
- exposes publish repositories convenience method
Related terraform:
```
***** Refreshing State and Upgrading Modules *****
Upgrading modules...
- uploads_module in ../../../../../../../pennsieve-go-api/terraform
Initializing the backend...
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding datadog/datadog versions matching "~> 2.23.0"...
- Finding newrelic/newrelic versions matching "~> 2.37.0"...
- Finding hashicorp/aws versions matching "5.50.0"...
- Using previously-installed datadog/datadog v2.23.0
- Using previously-installed newrelic/newrelic v2.37.0
- Using previously-installed hashicorp/aws v5.50.0
╷
│ Warning: Version constraints inside provider configuration blocks are deprecated
│ 
│   on providers.tf line 3, in provider "aws": …
```
> feature: exposes publish convenience method
