Pennsieve/pennsieve-go-api

- go.mod
- pkg/models/packageInfo/packageState/models.go
Updates the package state constants with a `Deleted` value to match the Scala `PackageState` enum.
Also adds a `Restoring` value we may need since restore jobs will be done asynchronously. This one is not in Scala yet.
> Add packageState consts for DELETED and RESTORING

- terraform/upload_service.yml
Updates the spec for GET /datasets/trashcan to reflect the fact that this now returns a dataset's deleted items one folder at a time.
If the new query param `root_node_id` is missing the returned list of items will be:
* deleted packages in the dataset's root folder
* folders in the dataset's root folder that have at deleted descendants
If `root_node_id` is present and is the id of a folder _F_ in the dataset, the returned list of items will be:
* deleted packages in _F_
* folders in _F_ that have deleted descendants
> Update OpenAPI spec for GET /datasets/trashcan

- terraform/upload_service.yml
The Action that creates our Readme documentation is failing because of OpenAPI validation errors. This should fix the errors.
This should only affect documentation, since AWS API Gateway does not look at response body specs when reading the OpenAPI file.
> Fixes for OpenAPI validation

- terraform/upload_service.yml
OpenAPI 3.0 introduced [new syntax for specifying Bearer authentication schemes](https://swagger.io/docs/specification/authentication/bearer-authentication/). This PR switches to that new syntax.
The problem with the current syntax is that it leads to incorrect documentation and generated code on https://docs.pennsieve.io/. That page shows the `Authorization` header without the `Bearer` portion of the header value which is not correct. It also generates incorrect code for the `CURL` examples because of the missing `Bearer`.
> Use OpenAPI 3.0 Bearer scheme for securityScheme values

- terraform/data.tf
- terraform/gateway.tf
- terraform/upload_service.yml
Adds a new service, readme-service to the Gateway API.
The new endpoint, `/readme/docs/{slug}` acts as a proxy for the readme.io API to return Pennsieve documents.
> Add readme-service to Gateway

- terraform/upload_service.yml
The public Discover API mostly does not require authentication or authorization. The `/rehydrate` endpoint is part of this API, so this PR removes the requirement to provide an `Authorization` header when using the endpoint.
> Remove authentication and authorization from /rehydrate endpoint

- terraform/upload_service.yml
* Adding endpoint in "datasets-service" to get a presigned url to a manfiest file for unpublished datasets
> add endpoint for dataset manifest

- terraform/data.tf
- terraform/gateway.tf
- terraform/upload_service.yml
**Clickup Ticket:** [8688wm1xv](https://app.clickup.com/t/8688wm1xv)
Adds import-service Lambda to AWS API Gateway to service import manifest creation and management.
Added the `POST /import/manifest` endpoint with limited details for now just for testing purposes.
```
...
+   /import/manifest:
+     post:
+       summary: Create import manifest
+       description: |
+         Calls endpoint on import-service to create an import manifest
+       x-amazon-apigateway-integration:
+         $ref: '#/components/x-amazon-apigateway-integrations/import-service'
+       operationId: createImportManifest
+       tags:
+         - Import Service
+       requestBody:
+         description: Import Manifest
+         required: true
+         content:
+           application/json:
+ …
```
> 8688wm1xv add import-service to API Gateway

- terraform/upload_service.yml
The concept here is that there is one endpoint which will get repositories from all origins (GitHub, others which we don't yet support but may in the future) that the authenticated user has access to. These are then joined with the Pennsieve External Repositories to indicate status of tracking with details (dataset id, app id).
**GET** `/repositories`
Response:
```yaml
repositoriesResponse:
type: object
properties:
page:
type: integer
size:
type: integer
count:
type: integer
repos:
type: array
items:
$ref: "#/components/schemas/repository"
```
Repository:
```yaml
repository:
type: object
properties:
origin:
type: string
name:
type: string
full_name:
type: string
description:
type: string
url:
type: string
tracking:
type: boolean
type:
type: string
details:
type: object
properties: …
```
> Add "Get My Repos" endpoint

- terraform/upload_service.yml
Added the following endpoints:
- **PUT** `/repository/external` for updating en External Repository
- **POST** `/repository/publis` to request publishing of an External Repository
> Two new Endpoints to support Code Repos

- lambda/authorizer/handler/handler.go
Check that `manifestId` and `datasetNodeId `are not the empty string before trying to use them.
Analysis in [ClickUp ticket](https://app.clickup.com/t/868a5xc7c).
> Fix for High Error Rate in API Gateway Authorizer

- lambda/authorizer/factory/factory.go
- lambda/authorizer/factory/factory_test.go
- lambda/authorizer/handler/handler.go
- lambda/authorizer/helpers/helpers.go
- lambda/authorizer/helpers/helpers_test.go
- lambda/authorizer/service/identity_source_service.go
- terraform/upload_service.yml
- refactor authorizer to use a combination of identity source and query params (particularly for manifest_id)
> fix: refactors to remove static identity source

- terraform/cloudwatch.tf
- sends logs to datadog
Background:
- I think this was originally commented out as it broke the build, as the log group already existed (perhaps historically added manually). This change uses the already existent log group to enable sending logs to datadog.
> fix: sends logs to datadog

- lambda/authorizer/authorizers/dataset_authorizer.go
- lambda/authorizer/authorizers/manifest_authorizer.go
- lambda/authorizer/authorizers/user_authorizer.go
- lambda/authorizer/authorizers/workspace_authorizer.go
- lambda/authorizer/factory/factory.go
- lambda/authorizer/handler/handler.go
PR creates a structured logger in the authorizer handler to improve log searches.
Also centralizes all error logging to the handler function, so that other functions only return detailed errors instead of logging them themselves. Updates these errors to include the initial error so that info is no longer lost.
> Create a structured logger in authorizer handler 

- Dockerfile.test
- lambda/authorizer/authorizers/authorizer.go
- lambda/authorizer/authorizers/dataset_authorizer.go
- lambda/authorizer/authorizers/dataset_authorizer_test.go
- lambda/authorizer/authorizers/manifest_authorizer.go
- lambda/authorizer/authorizers/manifest_authorizer_test.go
- lambda/authorizer/authorizers/user_authorizer.go
- lambda/authorizer/authorizers/user_authorizer_test.go
- lambda/authorizer/authorizers/workspace_authorizer.go
- lambda/authorizer/authorizers/workspace_authorizer_test.go
- lambda/authorizer/go.mod
- lambda/authorizer/go.sum
- lambda/authorizer/mocks/mocks.go
This updates Pennsieve Go API - in particular, the Authorizer - to use Pennsieve Go Core v1.13.0. The primary change is to use the const labels for the claim types. Note that the Authorizer implementations here directly return `map[string]interface{}` and do not user the `Claims` struct defined in Pennsieve Go Core; the AWS Event Response `Context` expects this. 
Test refactored:
1. switch the *expected* and *actual* values in the assertions
2. use the `String()` method on the Claim types
> Update to Pennsieve Go Core v1.13.0

- lambda/authorizer/go.mod
The previous build failed with:
```
go: downloading go1.22 (linux/amd64)
go: download go1.22 for linux/amd64: toolchain not available
```
A little research found this StackOverflow article: [`toolchain not available` error prevents me from using any go commands](https://stackoverflow.com/questions/78519711/toolchain-not-available-error-prevents-me-from-using-any-go-commands). The most up-voted answer suggests being more specific when specifying the Go version: 
> Fixed it by editing the go.mod file.
>
> changed go 1.22 to go 1.22.0
I am proposing to use the most recent version of the 1.22 branch, at this time it is 1.22.10.
> Set Go version to 1.22.10

- terraform/upload_service.yml
Fixes a typo in the OpenAPI YAML file that is causing the readme GitHub action to fail.
> Fix OpenAPI YAML file

- terraform/gateway.tf
- terraform/upload_service.yml
Adds `GET /applications/{id}/deployments` and `GET /applications/{id}/deployments/deploymentId` to the OpenAPI spec. These endpoints are configured to use the workspace authorizer.
Also updates the documented return types of `POST /applications` and `POST /applications/deploy` to match current prod reality.
Updates `aws_apigatewayv2_api.name` and `.description` in Terraform to reflect that the AWS API Gateway defined here is not just the upload service.
> Add application deploy status endpoints

- terraform/upload_service.yml
**ClickUp Ticket:** [868cdq5ce](https://app.clickup.com/t/868cdq5ce)
**Related PR:** https://github.com/Pennsieve/integration-service/pull/63
Update the API response models for workflow instances to match what the integration-service returns:
- new `status` field on workflow instances
- `processors -> workflow` in workflow instance status response for consistency across endpoints
> 868cdq5ce update workflow instance models

- terraform/upload_service.yml
Deprecate the old metadata service routes that conflict with new metadata service routes
- https://github.com/Pennsieve/model-service-serverless/pull/10
- https://github.com/Pennsieve/pennsieve-app/pull/404
> rename legacy metadata routes

- terraform/upload_service.yml
exposes PUT /workflows/{uuid} endpoint
Ran terraform plan locally, relevant changes:
```
'5XX':
$ref: '#/components/responses/Error'
+     put:
+       summary: Update the workflow properties
+       description: |
+         Update the isActive property of a workflow
+       x-amazon-apigateway-integration:
+         $ref: '#/components/x-amazon-apigateway-integrations/integration-service'
+       operationId: updateWorkflow
+       security:
+         - token_auth: [ ]
+       tags:
+         - Integration Service
+       parameters:
+         - in: path
+           name: id
+           required: true
+           schema:
+             type: string
+           description: The uuid of the workflow
+       requestBody:
+         description: Payload
+         required: true
+ …
```
> feature: exposes PUT /workflows/{uuid} endpoint
